### ISSUE TITLE
CSRF  problem on uploading 

### ISSUE THREAD

**Issue by bartzushka** [rob006/yii-elfinder2#5]

**Comment by rob006** [comment]
Please try current 1.1 branch and check if it solves your issue.

**Comment by bartzushka** [comment]
ok i tried to change that, but than i got another problem.. my files doesn`t show but it shows the ftp where i cant upload anything

**Comment by rob006** [comment]
Do you have any errors in JavaScript console?
Can you share your connector config?

**Comment by bartzushka** [comment]
there are no erorrs 
`

    // don't forget configure access rules

    public function actions() {
        return array(
            // main action for elFinder connector
            'connector' => array(
                'class' => 'ext.elFinder.ElFinderConnectorAction',
                // elFinder connector configuration
                // https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
                'settings' => array(
                    'roots' => array(
                        array(
                            'driver' => 'LocalFileSystem',
                            'path' => Yii::getPathOfAlias('webroot') . '/public/files/',
                            'URL' => Yii::app()->baseUrl . '/public/files/',
                            'alias' => 'files',
                            'acceptedName' => '/^[^\.].*$/', // disable creating dotfiles
                            'attributes' => array(
                                array(
                                    'pattern' => '/\/[.].*$/', // hide dotfiles
                                    'read' => true,
                                    'write' => true,
                                    'hidden' => true,
                                ),
                            ),
                        )
                    ),
                )
            ),
            // action for TinyMCE popup with elFinder widget
            'elfinderTinyMce' => array(
                'class' => 'ext.elFinder.TinyMceElFinderPopupAction',
                'connectorRoute' => 'connector', // main connector action id
            ),
            // action for file input popup with elFinder widget
            'elfinderFileInput' => array(
                'class' => 'ext.elFinder.ServerFileInputElFinderPopupAction',
                'connectorRoute' => 'connector', // main connector action id
            ),
        );
    }



 
`

**Comment by rob006** [comment]
I have no idea, I've tested this config in my project and works fine. Make sure you correctly copied the new version of extension. You can also check elfinder responses, maybe you find a clue.

**Comment by bartzushka** [comment]
http://prntscr.com/a9dvo7  look its 1.0
http://prntscr.com/a9dvzm  its 1.1

**Comment by rob006** [comment]
Did you try check this in browser private/incognito mode?

**Comment by bartzushka** [comment]
ok i fixed this by 
install 1.0 then replaced 
ElFinderConnectorAction.php	
ElFinderHelper.php	
ElFinderWidget.php	
ServerFileInput.php	
ServerFileInputElFinderPopupAction.php	

from 1.1 version

**Comment by rob006** [comment]
Branches 1.0 and 1.1 are not fully compatible. Probably at the end of the week I will include this fix in 1.0 line, so you should switch to new release then. 

But this FTP issue is odd - in your config there is no configuration for FTP, so there should be no FTP root regardless of extension version.

**Comment by bartzushka** [comment]
Ftp dissapeared now
